// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"webgl","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AnimatedBusts","status":true,"description":"Allows animating pictures","parameters":{}},
{"name":"GALV_CharacterFrames","status":false,"description":"Enables map character sheets to have more frames per character.","parameters":{"Frame Speed Modifier":"f * 0.8"}},
{"name":"GALV_VisualNovelChoices","status":false,"description":"(v.1.6) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"700","Command Height":"48","Always Middle":"true","Message Gap":"0","Disabled Button":"3"}},
{"name":"GALV_MessageBackground","status":false,"description":"(v.2.0) Displays an image behind messages in place of the windowskin","parameters":{"Image Variable ID":"1","Disable Switch ID":"1"}},
{"name":"GALV_CFStepSE","status":false,"description":"(v.1.2) Adds step sound effects to Galv's Character Frames plugin","parameters":{"Step Frames":"1,5","Events":"true","-- Terrain Step SE --":"","Terrain 1":"","Terrain 2":"","Terrain 3":"","Terrain 4":"","Terrain 5":"","Terrain 6":"","Terrain 7":""}},
{"name":"GALV_MessageBusts","status":true,"description":"(v.2.8) Displays a bust image instead of selected face image","parameters":{"Bust Priority":"0","Bust Position":"0","Text X Offset":"390","Fade Out Speed":"32","Filename Append":""}},
{"name":"DisableMouse","status":true,"description":"Disables mouse clicks.","parameters":{}},
{"name":"GALV_ActionIndicators","status":true,"description":"Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"Y Offset":"0","Z Position":"5","Auto Hide":"true","Icon Opacity":"200"}},
{"name":"KhasAdvancedLighting","status":false,"description":"[3.2] Adds lighting to your game.","parameters":{"Custom Blending":"ON","Transfer Reset":"OFF","Auto Battle Lighting":"ON"}},
{"name":"KhasHintSystem","status":false,"description":"[1.0] Hint/Tutorial System","parameters":{"Font name":"Arial","Font size":"16","Title bold":"OFF","Title italic":"OFF","Message bold":"OFF","Message italic":"OFF","Title color":"#ff9009","Message color":"#ffffff","Background color":"#000000","Background opacity":"70","Maximum width":"192","Margin":"4","Range":"192","Fade":"96"}},
{"name":"KhasCore","status":false,"description":"[2.0] Required by Khas plugins.","parameters":{}},
{"name":"KhasGraphics","status":false,"description":"[1.0] Required by Khas graphics plugins.","parameters":{}}
];
